using System.Collections;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Text;
using System.Text.Json;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using Microsoft.Win32;

namespace AIWordPressManager.Desktop;

internal static class ProfessionalDataGridWorkspaceExperience
{
    private static readonly ConditionalWeakTable<DataGrid, GridState> States = new();

    [ModuleInitializer]
    internal static void Initialize()
    {
        EventManager.RegisterClassHandler(
            typeof(DataGrid),
            FrameworkElement.LoadedEvent,
            new RoutedEventHandler(OnGridLoaded),
            true);

        EventManager.RegisterClassHandler(
            typeof(DataGrid),
            FrameworkElement.UnloadedEvent,
            new RoutedEventHandler(OnGridUnloaded),
            true);
    }

    private static void OnGridLoaded(object sender, RoutedEventArgs e)
    {
        if (sender is not DataGrid grid) return;
        var state = States.GetValue(grid, current => new GridState(current));
        state.Attach();
    }

    private static void OnGridUnloaded(object sender, RoutedEventArgs e)
    {
        if (sender is not DataGrid grid || !States.TryGetValue(grid, out var state)) return;
        state.SaveLayout();
        state.Detach();
    }

    private sealed class GridState
    {
        private readonly DataGrid _grid;
        private bool _attached;
        private ContextMenu? _professionalMenu;

        internal GridState(DataGrid grid) => _grid = grid;

        internal void Attach()
        {
            if (_attached) return;
            _attached = true;

            _grid.AutoGeneratedColumns += OnColumnsChanged;
            _grid.ColumnReordered += OnColumnReordered;
            _grid.PreviewMouseRightButtonDown += OnPreviewRightClick;
            _grid.Sorting += OnSorting;

            RestoreLayout();
            EnsureContextMenu();
        }

        internal void Detach()
        {
            if (!_attached) return;
            _attached = false;
            _grid.AutoGeneratedColumns -= OnColumnsChanged;
            _grid.ColumnReordered -= OnColumnReordered;
            _grid.PreviewMouseRightButtonDown -= OnPreviewRightClick;
            _grid.Sorting -= OnSorting;
        }

        private void OnColumnsChanged(object? sender, EventArgs e)
        {
            RestoreLayout();
            EnsureContextMenu();
        }

        private void OnColumnReordered(object? sender, DataGridColumnEventArgs e) => SaveLayout();
        private void OnSorting(object? sender, DataGridSortingEventArgs e) => _grid.Dispatcher.BeginInvoke(SaveLayout);
        private void OnPreviewRightClick(object sender, System.Windows.Input.MouseButtonEventArgs e) => EnsureContextMenu();

        private void EnsureContextMenu()
        {
            var existing = _grid.ContextMenu;
            if (existing is not null && ReferenceEquals(existing, _professionalMenu))
            {
                RebuildColumnMenu();
                return;
            }

            _professionalMenu = existing ?? new ContextMenu();
            if (existing is null) _grid.ContextMenu = _professionalMenu;

            if (_professionalMenu.Items.OfType<MenuItem>().Any(item => Equals(item.Tag, "AIWM_PRO_GRID")))
            {
                RebuildColumnMenu();
                return;
            }

            if (_professionalMenu.Items.Count > 0)
                _professionalMenu.Items.Add(new Separator());

            var columns = new MenuItem { Header = "Columns", Tag = "AIWM_PRO_GRID_COLUMNS" };
            var copy = CreateItem("Copy selected rows", (_, _) => CopySelectedRows());
            var export = CreateItem("Export visible rows to CSV", (_, _) => ExportVisibleRows());
            var reset = CreateItem("Reset grid layout", (_, _) => ResetLayout());
            copy.Tag = export.Tag = reset.Tag = "AIWM_PRO_GRID";

            _professionalMenu.Items.Add(columns);
            _professionalMenu.Items.Add(copy);
            _professionalMenu.Items.Add(export);
            _professionalMenu.Items.Add(new Separator { Tag = "AIWM_PRO_GRID" });
            _professionalMenu.Items.Add(reset);
            _professionalMenu.Opened += (_, _) => RebuildColumnMenu();
            RebuildColumnMenu();
        }

        private static MenuItem CreateItem(string header, RoutedEventHandler click)
        {
            var item = new MenuItem { Header = header, Tag = "AIWM_PRO_GRID" };
            item.Click += click;
            return item;
        }

        private void RebuildColumnMenu()
        {
            if (_professionalMenu is null) return;
            var columnsMenu = _professionalMenu.Items.OfType<MenuItem>()
                .FirstOrDefault(item => Equals(item.Tag, "AIWM_PRO_GRID_COLUMNS"));
            if (columnsMenu is null) return;

            columnsMenu.Items.Clear();
            foreach (var column in _grid.Columns.OrderBy(column => column.DisplayIndex))
            {
                var item = new MenuItem
                {
                    Header = GetColumnHeader(column),
                    IsCheckable = true,
                    IsChecked = column.Visibility == Visibility.Visible,
                    StaysOpenOnClick = true
                };
                item.Click += (_, _) =>
                {
                    column.Visibility = item.IsChecked ? Visibility.Visible : Visibility.Collapsed;
                    SaveLayout();
                };
                columnsMenu.Items.Add(item);
            }
        }

        internal void SaveLayout()
        {
            try
            {
                var key = GetGridKey();
                var store = GridLayoutStore.Load();
                store[key] = new GridLayout(
                    _grid.Columns.Select(column => new GridColumnLayout(
                        GetColumnIdentity(column),
                        column.DisplayIndex,
                        column.ActualWidth > 0 ? column.ActualWidth : column.Width.DisplayValue,
                        column.Visibility == Visibility.Visible,
                        column.SortDirection?.ToString())).ToList());
                GridLayoutStore.Save(store);
            }
            catch
            {
                // Layout persistence must never break a screen.
            }
        }

        private void RestoreLayout()
        {
            try
            {
                var store = GridLayoutStore.Load();
                if (!store.TryGetValue(GetGridKey(), out var layout)) return;

                foreach (var saved in layout.Columns)
                {
                    var column = _grid.Columns.FirstOrDefault(candidate =>
                        string.Equals(GetColumnIdentity(candidate), saved.Identity, StringComparison.Ordinal));
                    if (column is null) continue;

                    column.Visibility = saved.Visible ? Visibility.Visible : Visibility.Collapsed;
                    if (saved.Width is > 24 and < 2400)
                        column.Width = new DataGridLength(saved.Width);

                    if (saved.DisplayIndex >= 0 && saved.DisplayIndex < _grid.Columns.Count)
                    {
                        try { column.DisplayIndex = saved.DisplayIndex; } catch { }
                    }

                    if (Enum.TryParse<System.ComponentModel.ListSortDirection>(saved.SortDirection, out var direction))
                        column.SortDirection = direction;
                }
            }
            catch
            {
                // Invalid or stale layout data is ignored.
            }
        }

        private void ResetLayout()
        {
            try
            {
                var store = GridLayoutStore.Load();
                store.Remove(GetGridKey());
                GridLayoutStore.Save(store);

                foreach (var column in _grid.Columns)
                {
                    column.Visibility = Visibility.Visible;
                    column.SortDirection = null;
                    column.Width = DataGridLength.Auto;
                }

                _grid.Items.SortDescriptions.Clear();
                ProfessionalNotificationCenter.Publish(
                    NotificationSeverity.Success,
                    "Grid layout reset",
                    $"The saved layout for {GetGridKey()} was removed.",
                    null,
                    "DataGrid Workspace");
            }
            catch (Exception ex)
            {
                ProfessionalNotificationCenter.Publish(
                    NotificationSeverity.Error,
                    "Grid layout reset failed",
                    ex.Message,
                    ex.ToString(),
                    "DataGrid Workspace");
            }
        }

        private void CopySelectedRows()
        {
            var rows = _grid.SelectedItems.Cast<object>().ToList();
            if (rows.Count == 0 && _grid.CurrentItem is not null) rows.Add(_grid.CurrentItem);
            if (rows.Count == 0) return;

            Clipboard.SetText(BuildDelimited(rows, '\t'));
            ProfessionalNotificationCenter.Publish(
                NotificationSeverity.Success,
                "Rows copied",
                $"Copied {rows.Count:N0} row(s) from {GetGridKey()}.",
                null,
                "DataGrid Workspace");
        }

        private void ExportVisibleRows()
        {
            var rows = _grid.Items.Cast<object>().Where(item => item != CollectionView.NewItemPlaceholder).ToList();
            var dialog = new SaveFileDialog
            {
                Title = "Export grid to CSV",
                Filter = "CSV files (*.csv)|*.csv|All files (*.*)|*.*",
                FileName = $"{SanitizeFileName(GetGridKey())}_{DateTime.Now:yyyyMMdd_HHmmss}.csv",
                AddExtension = true,
                DefaultExt = ".csv"
            };
            if (dialog.ShowDialog(Window.GetWindow(_grid)) != true) return;

            try
            {
                File.WriteAllText(dialog.FileName, "\uFEFF" + BuildDelimited(rows, ','), Encoding.UTF8);
                ProfessionalNotificationCenter.Publish(
                    NotificationSeverity.Success,
                    "Grid exported",
                    $"Exported {rows.Count:N0} row(s) to {dialog.FileName}.",
                    null,
                    "DataGrid Workspace");
            }
            catch (Exception ex)
            {
                ProfessionalNotificationCenter.Publish(
                    NotificationSeverity.Error,
                    "Grid export failed",
                    ex.Message,
                    ex.ToString(),
                    "DataGrid Workspace");
            }
        }

        private string BuildDelimited(IReadOnlyCollection<object> rows, char delimiter)
        {
            var columns = _grid.Columns
                .Where(column => column.Visibility == Visibility.Visible)
                .OrderBy(column => column.DisplayIndex)
                .ToList();
            var builder = new StringBuilder();
            builder.AppendLine(string.Join(delimiter, columns.Select(column => Escape(GetColumnHeader(column), delimiter))));
            foreach (var row in rows)
            {
                builder.AppendLine(string.Join(delimiter, columns.Select(column =>
                    Escape(ReadValue(row, column), delimiter))));
            }
            return builder.ToString();
        }

        private static string ReadValue(object row, DataGridColumn column)
        {
            try
            {
                if (column is DataGridBoundColumn { Binding: Binding binding } && binding.Path?.Path is { Length: > 0 } path)
                {
                    object? current = row;
                    foreach (var segment in path.Split('.'))
                    {
                        if (current is null) break;
                        current = current.GetType().GetProperty(segment, BindingFlags.Instance | BindingFlags.Public | BindingFlags.IgnoreCase)
                            ?.GetValue(current);
                    }
                    return current?.ToString() ?? string.Empty;
                }

                var content = column.GetCellContent(row);
                return content switch
                {
                    TextBlock text => text.Text,
                    TextBox textBox => textBox.Text,
                    ContentControl control => control.Content?.ToString() ?? string.Empty,
                    _ => content?.ToString() ?? string.Empty
                };
            }
            catch
            {
                return string.Empty;
            }
        }

        private string GetGridKey()
        {
            var owner = Window.GetWindow(_grid)?.GetType().Name ?? "Application";
            var view = _grid.DataContext?.GetType().Name ?? "NoDataContext";
            var name = string.IsNullOrWhiteSpace(_grid.Name) ? "Grid" : _grid.Name;
            return $"{owner}.{view}.{name}";
        }

        private static string GetColumnHeader(DataGridColumn column) => column.Header?.ToString() ?? GetColumnIdentity(column);

        private static string GetColumnIdentity(DataGridColumn column)
        {
            if (column is DataGridBoundColumn { Binding: Binding binding } && binding.Path?.Path is { Length: > 0 } path)
                return path;
            return column.SortMemberPath is { Length: > 0 } sortPath ? sortPath : column.Header?.ToString() ?? $"Column{column.DisplayIndex}";
        }

        private static string Escape(string? value, char delimiter)
        {
            value ??= string.Empty;
            var needsQuotes = value.Contains(delimiter) || value.Contains('"') || value.Contains('\r') || value.Contains('\n');
            value = value.Replace("\"", "\"\"");
            return needsQuotes ? $"\"{value}\"" : value;
        }

        private static string SanitizeFileName(string value)
        {
            foreach (var invalid in Path.GetInvalidFileNameChars()) value = value.Replace(invalid, '_');
            return value;
        }
    }

    private sealed record GridColumnLayout(string Identity, int DisplayIndex, double Width, bool Visible, string? SortDirection);
    private sealed record GridLayout(List<GridColumnLayout> Columns);

    private static class GridLayoutStore
    {
        private static readonly object Sync = new();
        private static readonly string StorePath = Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
            "AIWordPressManager", "Workspace", "grid-layouts.json");

        internal static Dictionary<string, GridLayout> Load()
        {
            lock (Sync)
            {
                try
                {
                    if (!File.Exists(StorePath)) return new(StringComparer.Ordinal);
                    return JsonSerializer.Deserialize<Dictionary<string, GridLayout>>(File.ReadAllText(StorePath))
                           ?? new Dictionary<string, GridLayout>(StringComparer.Ordinal);
                }
                catch
                {
                    return new Dictionary<string, GridLayout>(StringComparer.Ordinal);
                }
            }
        }

        internal static void Save(Dictionary<string, GridLayout> store)
        {
            lock (Sync)
            {
                Directory.CreateDirectory(Path.GetDirectoryName(StorePath)!);
                File.WriteAllText(StorePath, JsonSerializer.Serialize(store, new JsonSerializerOptions
                {
                    WriteIndented = true
                }));
            }
        }
    }
}
