using AIWordPressManager.Application.Abstractions;
using AIWordPressManager.Application.Changes;
using AIWordPressManager.Application.Settings;
using Microsoft.Extensions.Logging;

namespace AIWordPressManager.AI;

public sealed class MultiProviderSuggestionProvider(
    IEnumerable<IAiProvider> providers,
    IApplicationSettingsService settingsService,
    ISecretProtectionService secretProtectionService,
    ILogger<MultiProviderSuggestionProvider> logger) : IAiSuggestionProvider
{
    private readonly IReadOnlyDictionary<string, IAiProvider> _providers = providers.ToDictionary(x => x.Name, StringComparer.OrdinalIgnoreCase);

    public Task<bool> IsConfiguredAsync(CancellationToken cancellationToken = default) => Task.FromResult(true);

    public async Task<IReadOnlyList<AiSuggestionOutput>> ImproveSuggestionsAsync(
        IReadOnlyCollection<AiSuggestionInput> suggestions,
        CancellationToken cancellationToken = default)
    {
        var settings = await settingsService.GetAiSettingsAsync(cancellationToken);
        if (!settings.Enabled)
            return CreateActionableLocalSuggestions(suggestions, "AI providers are disabled; generated by the built-in actionable recommendation engine.");

        var configured = settings.Providers
            .Where(x => x.Enabled && _providers.ContainsKey(x.Provider) && ((x.Provider.Equals("Ollama", StringComparison.OrdinalIgnoreCase) || x.Provider.Equals("Puter", StringComparison.OrdinalIgnoreCase)) || x.HasApiKey))
            .OrderBy(x => x.Priority)
            .ToArray();

        if (configured.Length == 0)
            return CreateActionableLocalSuggestions(suggestions, "No external or local AI provider is configured; generated by the built-in actionable recommendation engine.");

        var errors = new List<string>();
        foreach (var providerSettings in configured)
        {
            var provider = _providers[providerSettings.Provider];
            var apiKey = string.Empty;
            try
            {
                if (!provider.Name.Equals("Ollama", StringComparison.OrdinalIgnoreCase) && !provider.Name.Equals("Puter", StringComparison.OrdinalIgnoreCase))
                    apiKey = await secretProtectionService.UnprotectAsync(providerSettings.ProtectedApiKey, cancellationToken);

                logger.LogInformation("Generating AI suggestions with {Provider} using {Model}.", provider.Name, providerSettings.Model);
                var result = await provider.ImproveSuggestionsAsync(suggestions, providerSettings.Model, apiKey, cancellationToken);
                if (result.Count > 0)
                    return result.Select(x => x with { Reason = $"[AI:{provider.Name}] {x.Reason}" }).ToArray();
                errors.Add($"{provider.Name}: returned no suggestions.");
            }
            catch (Exception ex)
            {
                logger.LogWarning(ex, "AI provider {Provider} failed; trying the next provider.", provider.Name);
                errors.Add($"{provider.Name}: {ex.Message}");
                if (!settings.AutomaticFallback) break;
            }
            finally
            {
                apiKey = string.Empty;
            }
        }

        logger.LogWarning("All configured AI providers failed. Falling back to the built-in actionable engine. {Errors}", string.Join(" | ", errors));
        return CreateActionableLocalSuggestions(suggestions, "All configured AI providers were unavailable; generated locally so the workflow can continue.");
    }

    private static IReadOnlyList<AiSuggestionOutput> CreateActionableLocalSuggestions(
        IReadOnlyCollection<AiSuggestionInput> suggestions,
        string fallbackReason)
    {
        return suggestions.Select(input =>
        {
            var proposed = string.IsNullOrWhiteSpace(input.ProposedValue)
                ? BuildConcreteProposal(input)
                : input.ProposedValue.Trim();

            var reasonText = string.IsNullOrWhiteSpace(input.Reason)
                ? fallbackReason
                : $"{input.Reason.Trim()} {fallbackReason}";
            var reason = $"[AI:Rules Engine] {reasonText}";

            return new AiSuggestionOutput(
                input.ObjectId,
                input.ChangeType,
                proposed,
                reason,
                0.72,
                NormalizeRisk(input.RiskLevel));
        }).ToArray();
    }

    private static string BuildConcreteProposal(AiSuggestionInput input) => input.ChangeType switch
    {
        "SetTitle" => string.IsNullOrWhiteSpace(input.CurrentValue) ? "Create a concise, descriptive SEO title of no more than 60 characters." : input.CurrentValue.Trim(),
        "SetSlug" => Slugify(input.CurrentValue),
        "SetExcerpt" => "Add a factual 120–155 character summary that states the page topic and reader benefit.",
        "ReplaceBrokenLink" => "Remove the broken hyperlink while preserving its visible anchor text until a verified replacement URL is selected.",
        "ReviewEmptyCategory" => "Keep the category unpublished from navigation, identify the closest relevant parent category, then merge only after approval and redirect validation.",
        "StrengthenCategory" => "Assign at least two directly relevant existing posts or create supporting drafts before exposing this category prominently.",
        _ => $"Apply a specific correction for {input.ChangeType} to this item, preview the exact before/after value, and execute only after approval."
    };

    private static string Slugify(string value)
    {
        if (string.IsNullOrWhiteSpace(value)) return "generate-a-concise-descriptive-slug";
        var slug = System.Text.RegularExpressions.Regex.Replace(value.ToLowerInvariant(), @"[^\p{L}\p{Nd}]+", "-").Trim('-');
        return slug.Length <= 70 ? slug : slug[..70].Trim('-');
    }

    private static string NormalizeRisk(string? value) =>
        value?.Equals("High", StringComparison.OrdinalIgnoreCase) == true ? "High" :
        value?.Equals("Medium", StringComparison.OrdinalIgnoreCase) == true ? "Medium" : "Low";
}
